config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: ['my_rule_set', '.*>.*>[my_property]']
  excludes: []

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
#     - 'ProjectStatisticsReport'
#     - 'ComplexityReport'
     - 'NotificationReport'
     - 'IssuesReport'
     - 'FileBasedIssuesReport'
  #  - 'LiteIssuesReport'

output-reports:
  active: false
  exclude:
  # - 'XmlOutputReport'
  # - 'HtmlOutputReport'
  # - 'MdOutputReport'
  # - 'sarif'

comments:
  active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: true
    ignoreDefaultCompanionObject: true
    excludes:
      - '**/test/**'
  UndocumentedPublicFunction:
    active: true
    excludes:
      - '**/test/**'
  UndocumentedPublicProperty:
    active: true
    excludes:
      - '**/test/**'

complexity:
  active: true
  CognitiveComplexMethod:
    active: true
    allowedComplexity: 15
  ComplexCondition:
    active: true
    allowedConditions: 3
  ComplexInterface:
    active: true
    allowedDefinitions: 10
    includeStaticDeclarations: false
    includePrivateDeclarations: false
    ignoreOverloaded: false
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 14
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
    ignoreLocalFunctions: false
    nestingFunctions:
      - 'also'
      - 'apply'
      - 'forEach'
      - 'isNotNull'
      - 'ifNull'
      - 'let'
      - 'run'
      - 'use'
      - 'with'
  LabeledExpression:
    active: true
    ignoredLabels: []
  LargeClass:
    active: true
    allowedLines: 600
  LongMethod:
    active: true
    allowedLines: 60
  LongParameterList:
    active: true
    allowedFunctionParameters: 5
    allowedConstructorParameters: 6
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []
  MethodOverloading:
    active: true
    allowedOverloads: 6
  NamedArguments:
    active: true
    allowedArguments: 3
    ignoreArgumentsMatchingNames: false
  NestedBlockDepth:
    active: true
    allowedDepth: 4
  NestedScopeFunctions:
    active: true
    allowedDepth: 1
    functions:
      - 'kotlin.apply'
      - 'kotlin.run'
      - 'kotlin.with'
      - 'kotlin.let'
      - 'kotlin.also'
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: true
    allowedDuplications: 2
    ignoreAnnotation: true
    allowedWithLengthLessThan: 5
    ignoreStringsRegex: '$^'
    excludes:
      - '**/test/**'
  TooManyFunctions:
    active: true

coroutines:
  active: true
  CoroutineLaunchedInTestWithoutRunTest:
    active: false
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  ErrorUsageWithThrowable:
    active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames:
      - 'equals'
      - 'finalize'
      - 'hashCode'
      - 'toString'
  InstanceOfCheckForException:
    active: true

naming:
  active: true
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are)'
  ClassNaming:
    active: true
    aliases: ['ClassName']
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    aliases: ['EnumEntryName']
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  FunctionNameMaxLength:
    active: true
    aliases: ['FunctionMaxNameLength']
    maximumFunctionNameLength: 30
  InvalidPackageDeclaration:
    active: true
    aliases: ['PackageDirectoryMismatch']
    rootPackage: 'eu.magicksource.kiniconfig'
    requireRootInDeclaration: true
  LambdaParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*|_'
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 64
  VariableNaming:
    active: true
    aliases: ['PropertyName']
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true
    allowedOperations: 2
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTypeCasting:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
    forbiddenTypePatterns:
      - 'kotlin.String'
  CastNullableToNonNullableType:
    active: true
    ignorePlatformTypes: true

style:
  active: true
  CanBeNonNullable:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
    conversionFunctionPrefix:
      - 'to'
      - 'get'
    allowOperators: true
  DataClassShouldBeImmutable:
    active: true
  DoubleNegativeExpression:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true
  ForbiddenAnnotation:
    active: true
    annotations:
      - reason: 'it is a java annotation. Use `Suppress` instead.'
        value: 'java.lang.SuppressWarnings'
      - reason: 'it is a java annotation. Use `kotlin.Deprecated` instead.'
        value: 'java.lang.Deprecated'
      - reason: 'it is a java annotation. Use `kotlin.annotation.MustBeDocumented` instead.'
        value: 'java.lang.annotation.Documented'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Target` instead.'
        value: 'java.lang.annotation.Target'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Retention` instead.'
        value: 'java.lang.annotation.Retention'
      - reason: 'it is a java annotation. Use `kotlin.annotation.Repeatable` instead.'
        value: 'java.lang.annotation.Repeatable'
      - reason: 'Kotlin does not support @Inherited annotation, see https://youtrack.jetbrains.com/issue/KT-22265'
        value: 'java.lang.annotation.Inherited'
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
      - reason: 'Forbidden TODO todo marker in comment, please do the changes.'
        value: 'TODO:'
    allowedPatterns: 'TODO(\#\d+):'
  MandatoryBracesLoops:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 4
    allowNonStandardGrouping: false
  UnnecessaryParentheses:
    active: true
    allowForUnclearPrecedence: true
  UnusedImport:
    active: true
    additionalOperatorSet: []
  UseDataClass:
    active: true
    allowVars: false
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
    ignoreWhenContainingVariableDeclaration: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
